import type { DashboardStat, FranchiseBrand, LeadRecord, PackageInterest } from "@/lib/types";

export const franchiseCatalog: FranchiseBrand[] = [
  {
    brandId: "kargabites_siomai",
    brandName: "KargaBites Siomai Cart",
    category: "food_cart",
    capitalMin: 30000,
    capitalMax: 80000,
    trendSignal: "Food and beverage remains the strongest and most familiar franchise category.",
    locationSignal: "Best for terminals, schools, and high-foot-traffic areas.",
    riskSignal: "Needs daily operations discipline and stable foot traffic.",
    salesPitch: "A low-capital starter lane for first-time operators in busy local zones.",
    strongProvinces: ["Cebu", "Davao", "Pampanga", "Laguna", "Cavite"],
    trending: true,
    paybackEstimate: "6 to 10 months",
    managementStyle: "hands_on",
  },
  {
    brandId: "brewbay_coffee",
    brandName: "BrewBay Coffee Kiosk",
    category: "coffee_beverage",
    capitalMin: 150000,
    capitalMax: 350000,
    trendSignal: "Coffee and beverage kiosks are gaining traction among commuters and office workers.",
    locationSignal: "Best near schools, offices, transport hubs, and malls.",
    riskSignal: "Requires repeat traffic and high location quality.",
    salesPitch: "A trend-forward kiosk for buyers with a real foot-traffic thesis.",
    strongProvinces: ["NCR", "Cebu", "Davao", "Iloilo", "Pampanga"],
    trending: true,
    paybackEstimate: "10 to 16 months",
    managementStyle: "hands_on",
  },
  {
    brandId: "labago_laundry",
    brandName: "LabaGo Laundry Hub",
    category: "essential_service",
    capitalMin: 500000,
    capitalMax: 1200000,
    trendSignal: "Service franchises are gaining traction in residential and provincial demand.",
    locationSignal: "Best for condos, dorms, and dense residential communities.",
    riskSignal: "Needs reliable utilities and a trusted local operator.",
    salesPitch: "A practical lane for OFW investors seeking a process-driven business.",
    strongProvinces: ["Pampanga", "Cavite", "Laguna", "Bulacan", "Cebu", "Batangas"],
    trending: true,
    paybackEstimate: "14 to 22 months",
    managementStyle: "semi_passive",
  },
];

export const dashboardStats: DashboardStat[] = [
  {
    label: "Total Leads",
    value: "1,248",
    subtext: "+12% from last month",
    tone: "success",
  },
  {
    label: "High-Intent (Score > 80)",
    value: "342",
    subtext: "Verified AI Matching",
    tone: "gold",
  },
  {
    label: "Total Contract Value",
    value: "₱4.2M",
    subtext: "Projected Annual Pipeline",
    tone: "navy",
  },
];

export const packagePerformance: PackageInterest[] = [
  { label: "Express Food Cart Bundle", percent: 42, tone: "navy" },
  { label: "Pharma-Tech Franchise", percent: 28, tone: "gold" },
  { label: "Logistics Hub Premium", percent: 18, tone: "slate" },
  { label: "Agri-Grow Micro Mart", percent: 12, tone: "green" },
];

export const leadRecords: LeadRecord[] = [
  {
    leadId: "lead-ricardo-torres",
    investorName: "Ricardo Torres",
    email: "ricardo.torres@email.com",
    phone: "0917 123 4567",
    customerType: "ofw",
    customerLabel: "OFW (Middle East)",
    budgetText: "₱250K - ₱600K",
    budgetValue: 500000,
    preferredIndustry: "Food Cart",
    targetLocation: "Quezon City",
    aiScore: 94,
    scoreLabel: "High Match",
    stage: "hot_lead",
    lastActivity: "2h ago",
    channel: "Voice AI Call",
    actionLabel: "View Profile",
    recommendedBrand: "BrewBay Coffee Kiosk",
    recommendationReason:
      "Budget, target location, and daily hands-on readiness align with beverage kiosk demand.",
    marketSignal: "Coffee kiosks are trending in high-foot-traffic metro corridors.",
    managementStyle: "hands_on",
    timeline: "1 to 3 months",
    riskFlags: ["Location quality must be verified", "Daily staffing consistency required"],
    transcriptPreview: [
      "Maya: Can you share your budget and target area?",
      "Buyer: Around five hundred thousand, Quezon City.",
      "Maya: BrewBay is the strongest fit for your profile right now.",
    ],
  },
  {
    leadId: "lead-maria-santos",
    investorName: "Maria Santos",
    email: "maria.santos@email.com",
    phone: "0908 987 6543",
    customerType: "local",
    customerLabel: "In Consultation",
    budgetText: "₱900K - ₱1.5M",
    budgetValue: 1200000,
    preferredIndustry: "Laundry",
    targetLocation: "Pampanga",
    aiScore: 89,
    scoreLabel: "High Match",
    stage: "in_consultation",
    lastActivity: "1h ago",
    channel: "AI Consultation",
    actionLabel: "Open Transcript",
    recommendedBrand: "LabaGo Laundry Hub",
    recommendationReason:
      "Capital readiness and location profile match service demand for residential districts.",
    marketSignal: "Service franchises continue to gain traction in provincial communities.",
    managementStyle: "family_managed",
    timeline: "3 to 6 months",
    riskFlags: ["Utility reliability assessment needed"],
    transcriptPreview: [
      "Maya: You mentioned Pampanga and family-managed setup.",
      "Buyer: Yes, I want a stable service business.",
      "Maya: LabaGo aligns with your setup and timeline.",
    ],
  },
  {
    leadId: "lead-juan-garcia",
    investorName: "Juan Garcia",
    email: "juan.garcia@email.com",
    phone: "0916 456 7890",
    customerType: "ofw",
    customerLabel: "OFW (USA)",
    budgetText: "₱200K - ₱400K",
    budgetValue: 300000,
    preferredIndustry: "Water Refilling",
    targetLocation: "Cebu City",
    aiScore: 76,
    scoreLabel: "Good Match",
    stage: "new_lead",
    lastActivity: "5h ago",
    channel: "Form Submission",
    actionLabel: "Contact",
    recommendedBrand: "BrewBay Coffee Kiosk",
    recommendationReason:
      "Budget supports a kiosk model, but location validation is still required before final commitment.",
    marketSignal: "Beverage kiosks perform best in commuter zones with repeat volume.",
    managementStyle: "semi_passive",
    timeline: "2 to 4 months",
    riskFlags: ["Needs local operating partner", "Category preference still broad"],
    transcriptPreview: [
      "Maya: Are you planning to manage directly or through family?",
      "Buyer: Mostly remote. My cousin will operate.",
      "Maya: We should validate location before moving to consultation.",
    ],
  },
  {
    leadId: "lead-angela-cruz",
    investorName: "Angela Cruz",
    email: "angela.cruz@email.com",
    phone: "0921 654 3210",
    customerType: "local",
    customerLabel: "High Intent",
    budgetText: "₱600K - ₱1M",
    budgetValue: 850000,
    preferredIndustry: "Pharmacy",
    targetLocation: "Davao City",
    aiScore: 92,
    scoreLabel: "High Match",
    stage: "high_intent",
    lastActivity: "30m ago",
    channel: "Voice AI Call",
    actionLabel: "Review",
    recommendedBrand: "LabaGo Laundry Hub",
    recommendationReason:
      "Davao residential density and capital range support a service-format launch plan.",
    marketSignal: "Residential service franchises remain resilient in regional centers.",
    managementStyle: "hands_on",
    timeline: "1 to 2 months",
    riskFlags: ["Utility cost sensitivity"],
    transcriptPreview: [
      "Maya: Do you prefer food or essential service?",
      "Buyer: Essential service, lower spoilage risk.",
      "Maya: Then we should prioritize LabaGo for your profile.",
    ],
  },
  {
    leadId: "lead-jose-mendoza",
    investorName: "Jose P. Mendoza",
    email: "jose.mendoza@email.com",
    phone: "0932 111 2222",
    customerType: "local",
    customerLabel: "In Consultation",
    budgetText: "₱1M - ₱2M",
    budgetValue: 1500000,
    preferredIndustry: "Sari-Sari Store",
    targetLocation: "Batangas City",
    aiScore: 85,
    scoreLabel: "High Match",
    stage: "in_consultation",
    lastActivity: "3h ago",
    channel: "AI Consultation",
    actionLabel: "Open Transcript",
    recommendedBrand: "LabaGo Laundry Hub",
    recommendationReason:
      "Buyer has strong capital and favors a stable demand model for family-led operations.",
    marketSignal: "Provincial service categories are expanding with lower saturation.",
    managementStyle: "family_managed",
    timeline: "4 to 6 months",
    riskFlags: ["Site lease negotiations pending"],
    transcriptPreview: [
      "Maya: You can fund a higher-capital model comfortably.",
      "Buyer: I want a long-term family business.",
      "Maya: LabaGo gives the most operational stability for that goal.",
    ],
  },
];

export const filterOptions = {
  budget: ["All Budgets", "₱200K - ₱500K", "₱500K - ₱1M", "₱1M - ₱2M"],
  industry: ["All Industries", "Food Cart", "Laundry", "Water Refilling", "Pharmacy"],
  province: ["All Provinces", "Quezon City", "Pampanga", "Cebu City", "Davao City", "Batangas City"],
  score: ["All Scores", "90+", "80 - 89", "70 - 79"],
  status: ["All Statuses", "Hot Lead", "In Consultation", "New Lead", "High Intent"],
};
